### ISSUE TITLE
Bug: Unable to capture Thai translation 

### ISSUE THREAD

**Issue by madprogramer** [Data-Horde/ytcc-exporter#2]
I submitted a dummy contribution in Thai on [this video](https://www.youtube.com/watch?v=ri_0v9rHB_Q) to see if ytcc-exporter would be able to capture it.

```bash
> python ytcc-exporter.py ri_0v9rHB_Q
> ri_0v9rHB_Q has the following languages available en, en-GB, tr.
```

No luck ¯\\_(ツ)_/¯

**Comment by tech234a** [comment]
Perhaps I applied the wrong logic here... I had just pulled the languages the appear when the select language dropdown is first opened... I noticed that some languages in the extended dropdown say "Published", but is there any way to identify ones with drafts? It would be inefficient to check all of the languages, so I would only like to do that if required.

This video has a draft in English, and published Spanish and Turkish captions: https://www.youtube.com/timedtext_video?v=IjJKfe-0Ty0&ar=1600276037050

**Comment by tech234a** [comment]
Now uses a static list of all languages
